# Generated by Django 2.2.1 on 2019-05-02 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 7, 29, 15, 779832), verbose_name='date published'),
        ),
    ]
