# Generated by Django 2.2.1 on 2019-05-13 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190513_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialseries',
            old_name='series_summery',
            new_name='series_summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 8, 54, 41, 186263), verbose_name='date published'),
        ),
    ]
