# Generated by Django 2.2.1 on 2019-05-13 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190513_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorialcategory',
            old_name='category_summery',
            new_name='category_summary',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 8, 55, 44, 480848), verbose_name='date published'),
        ),
    ]
