# Generated by Django 2.2.1 on 2019-05-13 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190513_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 9, 13, 43, 193140), verbose_name='date published'),
        ),
    ]
