# Generated by Django 2.2.1 on 2019-05-14 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190514_1327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bool',
            new_name='Book',
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 14, 13, 50, 9, 442305), verbose_name='date published'),
        ),
    ]
